FROM l.gcr.io/google/bazel:3.0.0
RUN apt-get update && apt-get install -y --no-install-recommends \
 qtmultimedia5-dev \
 qttools5-dev \
 qttools5-dev-tools

RUN ["git", "clone", "--recurse-submodules",\
 "https://github.com/TokTok/toktok-stack", "/src/toktok-stack"]
WORKDIR /src/toktok-stack
RUN ["git", "submodule", "foreach", "--recursive", "git", "checkout", "master"]
RUN ["bazel", "query", ":all"]
COPY .bazelrc.local /src/toktok-stack/
